
export interface Generator {
    id: string;
    name: string;
    brand: string;
    powerKW: number;
    type: 'Silent' | 'Open' | 'Portable';
    image: string;
    inStock: boolean;
    description?: string;
    engineModel?: string;
    voltage?: string;
    phase?: string;
    fuelConsumption?: string;
    dimensions?: string;
    weight?: string;
    frequency?: string;
}

export interface WaterPump {
    id: string;
    name: string;
    brand?: string;
    type: 'Gasoline' | 'Diesel' | 'High Pressure' | 'Industrial';
    inletSize: string;
    maxHead: number;
    flowRate: number;
    image: string;
    inStock: boolean;
    description: string;
    specs: {
        suction: string;
        fuelTank: string;
        engineModel: string;
        startSystem: string;
    }
}

export const GENERATORS: Generator[] = [
    {
        id: 'mdz-30ds',
        name: 'CE Power MDZ30DS Soundproof',
        brand: 'CE Power',
        powerKW: 24,
        type: 'Silent',
        image: '/images/mindong-30ds.png',
        inStock: true,
        description: 'The MDZ series Soundproof generator set. Features an automatic/manual control function, intergral salient pole rotor technique, and world-famous brand engines.',
        voltage: '400/230V',
        phase: '3 Phase',
        fuelConsumption: '6.3 L/hr',
        dimensions: '2400 x 1000 x 1620 mm',
        weight: '1205 kg'
    },
    {
        id: 'mdz-110ds',
        name: 'CE Power MDZ110DS Soundproof',
        brand: 'CE Power',
        powerKW: 88,
        type: 'Silent',
        image: '/images/mindong-110ds.png',
        inStock: true,
        description: 'High-capacity soundproof generator set with advanced sound attenuation. Ideal for urban environments requiring stable power.',
        voltage: '400/230V',
        phase: '3 Phase',
        fuelConsumption: '22 L/hr',
        dimensions: '3000 x 1100 x 1720 mm',
        weight: '1944 kg'
    },
    {
        id: 'mdz-240yc',
        name: 'Yuchai MDZ240YC Industrial',
        brand: 'Yuchai',
        powerKW: 24.5,
        type: 'Open',
        image: '/images/yuchai-240yc.png',
        inStock: true,
        description: 'Powered by Yuchai engine, known for low noise, reliable emissions, and high-performance power strong accords with national environmental protection requirements.',
        voltage: '400/230V',
        phase: '3 Phase',
        fuelConsumption: '7.8 L/hr',
        dimensions: '1850 x 900 x 1200 mm',
        weight: '875 kg'
    },
    {
        id: 'mdz50ng',
        name: 'MDZ50NG Natural Gas',
        brand: 'Jichai',
        powerKW: 50,
        type: 'Silent',
        image: '/images/mdz50ng_natural_gas_1768809923679.png',
        inStock: true,
        description: 'High-efficiency natural gas generator powered by M4BTAA3.9-NG engine. Features electronic speed control and ECU ignition.',
        voltage: '400V',
        phase: '3-Phase',
        fuelConsumption: '14.5 m3/h',
        dimensions: '1900x750x1150 mm',
        weight: '1100 kg'
    },
    {
        id: 'mdz1400ck',
        name: 'MDZ1400CK High Voltage',
        brand: 'Cummins',
        powerKW: 1120,
        type: 'Silent',
        image: '/images/mdz1400ck_high_voltage_1768809965087.png',
        inStock: true,
        description: '10kV High Voltage generator set powered by KTA50-G3 engine. Designed for massive power requirements.',
        voltage: '10,000V',
        phase: '3-Phase',
        fuelConsumption: '290 L/h',
        dimensions: '5800x2200x2520 mm',
        weight: '12500 kg'
    },
    {
        id: 'mg2500',
        name: 'MG2500 Portable',
        brand: 'CE Power',
        powerKW: 2.5,
        type: 'Portable',
        image: '/images/mg2500_portable_gasoline_1768810001240.png',
        inStock: true,
        description: 'Compact and light weight gasoline generator. Perfect for small homes, camping, or mobile work stations.',
        voltage: '220V',
        phase: 'Single-Phase',
        fuelConsumption: '1.2 L/h',
        dimensions: '600x440x445 mm',
        weight: '43 kg'
    },
    {
        id: 'mk9500e',
        name: 'MK9500E Heavy Duty',
        brand: 'Kohler',
        powerKW: 9.5,
        type: 'Portable',
        image: '/images/mk9500e_heavy_duty_gasoline_1768810056926.png',
        inStock: true,
        description: 'Heavy duty portable gasoline generator equipped with Kohler CH640 engine. Features electric start.',
        voltage: '220V',
        phase: 'Single-Phase',
        fuelConsumption: '3.5 L/h',
        dimensions: '1010x630x695 mm',
        weight: '216 kg'
    },
    {
        id: 'mdz-30dk',
        name: 'Dongfeng Cummins MDZ30DK',
        brand: 'Cummins',
        powerKW: 24,
        type: 'Open',
        image: '/images/cummins-30dk.png',
        inStock: true,
        description: 'Dongfeng Cummins Generator set. Offers a wide variety of automotive and industrial power solutions.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '6.3 L/hr',
        dimensions: '1580 x 650 x 1146 mm',
        weight: '777 kg'
    },
    {
        id: 'mdz-275ck',
        name: 'Chongqing Cummins MDZ275CK',
        brand: 'Cummins',
        powerKW: 220,
        type: 'Silent',
        image: '/images/cummins-275ck.png',
        inStock: true,
        description: 'Chongqing Cummins high-power generation solution. Engineered for durability, safety, and emission control.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '47.5 L/hr',
        dimensions: '3000 x 1054 x 1758 mm',
        weight: '2460 kg'
    },
    {
        id: 'mdz-10pk',
        name: 'Perkins MDZ10PK Elite',
        brand: 'Perkins',
        powerKW: 8,
        type: 'Silent',
        image: '/images/perkins-10pk.png',
        inStock: true,
        description: 'Compact Perkins generator set. Perkins is world-famous for reliability and durability.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '3.0 L/hr',
        dimensions: '1360 x 670 x 1313 mm',
        weight: '220 kg'
    },
    {
        id: 'mdz-300mtu',
        name: 'MTU MDZ300MTU Power',
        brand: 'MTU',
        powerKW: 240,
        type: 'Open',
        image: '/images/mtu-300mtu.png',
        inStock: true,
        description: 'Powered by MTU engine from Germany Daimler MTU. Renowned for advanced and high power density.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '10.5 G/kW.H',
        dimensions: '3000 x 1450 x 1815 mm',
        weight: '2760 kg'
    },
    {
        id: 'mdz-93vo',
        name: 'Volvo MDZ93VO Series',
        brand: 'Volvo',
        powerKW: 75,
        type: 'Silent',
        image: '/images/volvo-93vo.png',
        inStock: true,
        description: 'Volvo series environment consciousness genset. Features quality, safety, and care for the environment.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '21.3 L/H',
        dimensions: '1940 x 900 x 1505 mm',
        weight: '1150 kg'
    },
    {
        id: 'me-11500e',
        name: 'CE Power ME11500E Gasoline',
        brand: 'CE Power',
        powerKW: 8.5,
        type: 'Portable',
        image: '/images/mindong-gasoline.png',
        inStock: true,
        description: 'Suitable for backup power for business stores, agricultural workshops, and shopping malls.',
        voltage: '220V',
        phase: 'Single Phase',
        fuelConsumption: '3.5 L/hr',
        dimensions: '800 x 630 x 844 mm',
        weight: '184 kg'
    },
    {
        id: 'weichai-80kw',
        name: 'Weichai 100kVA/80kW Generator',
        brand: 'Weichai',
        powerKW: 80,
        type: 'Silent',
        image: '/images/weichai-80kw.png',
        inStock: true,
        description: 'Reliable Weichai power generation for industrial use.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '20 L/hr',
        dimensions: '2200 x 900 x 1500 mm',
        weight: '1200 kg'
    },
    {
        id: 'weichai-80kw-open',
        name: 'Weichai 80kW Open Generator',
        brand: 'Weichai',
        powerKW: 80,
        type: 'Open',
        image: '/images/weichai-80kw-open.png',
        inStock: true,
        description: 'Cost-effective open type Weichai generator.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '20 L/hr',
        dimensions: '2100 x 850 x 1400 mm',
        weight: '1100 kg'
    },
    {
        id: 'weichai-500kw',
        name: 'Weichai 625kVA/500kW Generator',
        brand: 'Weichai',
        powerKW: 500,
        type: 'Silent',
        image: '/images/weichai-500kw.png',
        inStock: true,
        description: 'Heavy duty Weichai generator for large scale operations.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '105 L/hr',
        dimensions: '3500 x 1400 x 2000 mm',
        weight: '4500 kg'
    },
    {
        id: 'weichai-3000kw',
        name: 'Weichai 3750kVA/3000kW Generator',
        brand: 'Weichai',
        powerKW: 3000,
        type: 'Open',
        image: '/images/weichai-3000kw.png',
        inStock: true,
        description: 'Maximum power Weichai solution for power plants and grid support.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '600 L/hr',
        dimensions: '6000 x 2200 x 2800 mm',
        weight: '18000 kg'
    },
    {
        id: 'yuchai-100kw',
        name: 'Yuchai 125kVA/100kW Generator',
        brand: 'Yuchai',
        powerKW: 100,
        type: 'Silent',
        image: '/images/yuchai-100kw.png',
        inStock: true,
        description: 'Efficient Yuchai engine generator.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '24 L/hr',
        dimensions: '2400 x 1000 x 1600 mm',
        weight: '1350 kg'
    },
    {
        id: 'yuchai-100kw-open',
        name: 'Yuchai 100kW Open Generator',
        brand: 'Yuchai',
        powerKW: 100,
        type: 'Open',
        image: '/images/yuchai-100kw-open.png',
        inStock: true,
        description: 'Robust open-frame Yuchai generator for construction sites.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '24 L/hr',
        dimensions: '2300 x 950 x 1500 mm',
        weight: '1250 kg'
    },
    {
        id: 'yuchai-1000kw',
        name: 'Yuchai 1250kVA/1000kW Generator',
        brand: 'Yuchai',
        powerKW: 1000,
        type: 'Silent',
        image: '/images/yuchai-1000kw.png',
        inStock: true,
        description: 'High capacity Yuchai generator for industrial applications.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '210 L/hr',
        dimensions: '6058 x 2438 x 2591 mm',
        weight: '8000 kg'
    },
    {
        id: 'yuchai-2000kw',
        name: 'Yuchai 2500kVA/2000kW Generator',
        brand: 'Yuchai',
        powerKW: 2000,
        type: 'Silent',
        image: '/images/yuchai-2000kw.png',
        inStock: true,
        description: 'Massive power Yuchai unit for critical infrastructure.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '420 L/hr',
        dimensions: '12192 x 2438 x 2896 mm',
        weight: '15000 kg'
    },
    {
        id: 'perkins-100kw',
        name: 'Perkins 125kVA/100kW Generator',
        brand: 'Perkins',
        powerKW: 100,
        type: 'Silent',
        image: '/images/perkins-100kw.png',
        inStock: true,
        description: 'Classic UK design Perkins engine generator.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '22 L/hr',
        dimensions: '2500 x 1000 x 1600 mm',
        weight: '1400 kg'
    },
    {
        id: 'perkins-100kw-open',
        name: 'Perkins 100kW Open Generator',
        brand: 'Perkins',
        powerKW: 100,
        type: 'Open',
        image: '/images/perkins-100kw-open.png',
        inStock: true,
        description: 'Durable open type Perkins generator.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '22 L/hr',
        dimensions: '2400 x 950 x 1500 mm',
        weight: '1300 kg'
    },
    {
        id: 'perkins-1000kw',
        name: 'Perkins 1250kVA/1000kW Generator',
        brand: 'Perkins',
        powerKW: 1000,
        type: 'Silent',
        image: '/images/perkins-1000kw.png',
        inStock: true,
        description: 'Reliable high power Perkins generator.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '215 L/hr',
        dimensions: '6058 x 2438 x 2591 mm',
        weight: '9000 kg'
    },
    {
        id: 'perkins-2000kw',
        name: 'Perkins 2500kVA/2000kW Generator',
        brand: 'Perkins',
        powerKW: 2000,
        type: 'Silent',
        image: '/images/perkins-2000kw.png',
        inStock: true,
        description: 'Flagship Perkins power solution.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '430 L/hr',
        dimensions: '12192 x 2438 x 2896 mm',
        weight: '16000 kg'
    },
    {
        id: 'cummins-100kw',
        name: 'Cummins 125kVA/100kW Generator',
        brand: 'Cummins',
        powerKW: 100,
        type: 'Silent',
        image: '/images/cummins-100kw.png',
        inStock: true,
        description: 'Economical Cummins power.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '23 L/hr',
        dimensions: '2450 x 1000 x 1600 mm',
        weight: '1380 kg'
    },
    {
        id: 'cummins-1000kw',
        name: 'Cummins 1250kVA/1000kW Generator',
        brand: 'Cummins',
        powerKW: 1000,
        type: 'Silent',
        image: '/images/cummins-1000kw.png',
        inStock: true,
        description: 'Heavy duty Cummins KTA series engine.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '205 L/hr',
        dimensions: '6058 x 2438 x 2591 mm',
        weight: '8500 kg'
    },
    {
        id: 'mtu-1000kw',
        name: 'MTU 1250kVA/1000kW Generator',
        brand: 'MTU',
        powerKW: 1000,
        type: 'Silent',
        image: '/images/mtu-1000kw.png',
        inStock: true,
        description: 'German engineering MTU engine generator.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '195 L/hr',
        dimensions: '6058 x 2438 x 2591 mm',
        weight: '8200 kg'
    },
    {
        id: 'mtu-2000kw',
        name: 'MTU 2500kVA/2000kW Generator',
        brand: 'MTU',
        powerKW: 2000,
        type: 'Silent',
        image: '/images/mtu-2000kw.png',
        inStock: true,
        description: 'Advanced MTU series 4000 engine.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '390 L/hr',
        dimensions: '12192 x 2438 x 2896 mm',
        weight: '14800 kg'
    },
    {
        id: 'volvo-500kw',
        name: 'Volvo 625kVA/500kW Generator',
        brand: 'Volvo',
        powerKW: 500,
        type: 'Silent',
        image: '/images/volvo-500kw.png',
        inStock: true,
        description: 'High efficiency Volvo power.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '100 L/hr',
        dimensions: '3500 x 1400 x 2000 mm',
        weight: '4200 kg'
    },
    {
        id: 'yunnei-15kw',
        name: 'Yunnei 18kVA/15kW Generator',
        brand: 'Yunnei',
        powerKW: 15,
        type: 'Silent',
        image: '/images/yunnei-15kw.png',
        inStock: true,
        description: 'Compact Yunnei power for small businesses.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '4 L/hr',
        dimensions: '1600 x 700 x 1000 mm',
        weight: '600 kg'
    },
    {
        id: 'yunnei-50kw',
        name: 'Yunnei 63kVA/50kW Generator',
        brand: 'Yunnei',
        powerKW: 50,
        type: 'Silent',
        image: '/images/yunnei-50kw.png',
        inStock: true,
        description: 'Cost effective Yunnei generator.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '12 L/hr',
        dimensions: '2000 x 900 x 1300 mm',
        weight: '950 kg'
    },
    {
        id: 'yunnei-100kw',
        name: 'Yunnei 125kVA/100kW Generator',
        brand: 'Yunnei',
        powerKW: 100,
        type: 'Silent',
        image: '/images/yunnei-100kw.png',
        inStock: true,
        description: 'Powerful Yunnei solution.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '22 L/hr',
        dimensions: '2400 x 1000 x 1600 mm',
        weight: '1250 kg'
    },
    {
        id: 'kefo-50kw',
        name: 'Kefo 63kVA/50kW Generator',
        brand: 'Kefo',
        powerKW: 50,
        type: 'Silent',
        image: '/images/kefo-50kw.png',
        inStock: true,
        description: 'Standard Kefo power generator.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '12 L/hr',
        dimensions: '2000 x 900 x 1300 mm',
        weight: '920 kg'
    },
    {
        id: 'yuchai-150kw-md150',
        name: 'Yuchai MD150 Industrial',
        brand: 'Yuchai',
        powerKW: 150,
        type: 'Silent',
        image: '/images/yuchai-150kw-md150.png',
        inStock: true,
        description: 'Powered by Yuchai YC6A245L-D21 engine.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '44.7 L/hr',
        dimensions: '2450 x 1080 x 1770 mm',
        weight: '1220 kg'
    },
    {
        id: 'yuchai-200kw-md200',
        name: 'Yuchai MD-200 Industrial',
        brand: 'Yuchai',
        powerKW: 200,
        type: 'Silent',
        image: '/images/yuchai-200kw-md200.png',
        inStock: true,
        description: 'Powered by Yuchai YC6MK350L-D20 engine.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '63.6 L/hr',
        dimensions: '3600 x 1500 x 2200 mm',
        weight: '2900 kg'
    },
    {
        id: 'yuchai-250kw-mdz350',
        name: 'Yuchai MDZ350YC Industrial',
        brand: 'Yuchai',
        powerKW: 250,
        type: 'Silent',
        image: '/images/yuchai-250kw-mdz350.png',
        inStock: true,
        description: 'Powered by Yuchai YC6MK420L-D20 engine.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '77.6 L/hr',
        dimensions: '4000 x 1200 x 2020 mm',
        weight: '3100 kg'
    },
    {
        id: 'yunnei-600kw',
        name: 'Yunnei 600kW Generator',
        brand: 'Yunnei',
        powerKW: 600,
        type: 'Silent',
        image: '/images/yunnei-large-stock.png',
        inStock: true,
        description: 'High power Yunnei generator.',
        voltage: '400V',
        phase: '3 Phase'
    },
    {
        id: 'yunnei-400kw',
        name: 'Yunnei 400kW Generator',
        brand: 'Yunnei',
        powerKW: 400,
        type: 'Silent',
        image: '/images/yunnei-large-stock.png',
        inStock: true,
        description: 'Reliable Yunnei power.',
        voltage: '400V',
        phase: '3 Phase'
    },
    {
        id: 'weichai-400kw-new',
        name: 'Weichai 400kW Generator',
        brand: 'Weichai',
        powerKW: 400,
        type: 'Silent',
        image: '/images/weichai-500kw.png',
        inStock: true,
        description: 'Robust Weichai industrial generator.',
        voltage: '400V',
        phase: '3 Phase'
    },
    {
        id: 'last-200kw',
        name: 'Last 200kW Generator',
        brand: 'Last',
        powerKW: 200,
        type: 'Silent',
        image: '/images/last-brand-silent.png',
        inStock: true,
        description: 'Premium Last brand silent generator.',
        voltage: '400V',
        phase: '3 Phase'
    },
    {
        id: 'united-11kw',
        name: 'United Power 11kW Silent',
        brand: 'United Power',
        powerKW: 11,
        type: 'Silent',
        image: '/images/united-power-silent.png',
        inStock: true,
        description: 'Compact silent backup for small businesses.',
        voltage: '220/380V',
        phase: '3 Phase'
    },
    {
        id: 'yuchai-6-piston-gold',
        name: 'Yuchai 6-Piston Gold Refiner',
        brand: 'Yuchai',
        powerKW: 200,
        type: 'Silent',
        image: '/images/yuchai-200kw-md200.png',
        inStock: true,
        description: 'Specialized Yuchai 6-Piston engine generator designed for the continuous heavy load of gold refinement machinery.',
        voltage: '400V',
        phase: '3 Phase',
        fuelConsumption: '20L/hr',
        weight: '2800 kg'
    },
    // Adding more from the constants.ts Jan 2026 update
    { id: 'yunnei-334kw', name: 'Yunnei 334kW Generator', brand: 'Yunnei', powerKW: 334, type: 'Silent', image: '/images/yunnei-large-stock.png', inStock: true, description: 'Yunnei industrial generator.' },
    { id: 'yunnei-120kw-new', name: 'Yunnei 120kW Generator', brand: 'Yunnei', powerKW: 120, type: 'Silent', image: '/images/yunnei-100kw.png', inStock: true, description: 'Efficient Yunnei power.' },
    { id: 'yunnei-77kw', name: 'Yunnei 77kW Generator', brand: 'Yunnei', powerKW: 77, type: 'Silent', image: '/images/yunnei-80kw-mdz110.png', inStock: true, description: 'Yunnei generator.' },
    { id: 'yunnei-55kw', name: 'Yunnei 55kW Generator', brand: 'Yunnei', powerKW: 55, type: 'Silent', image: '/images/yunnei-50kw.png', inStock: true, description: 'Yunnei generator.' },
    { id: 'yunnei-38kw', name: 'Yunnei 38kW Generator', brand: 'Yunnei', powerKW: 38, type: 'Silent', image: '/images/yunnei-30kw-md40.png', inStock: true, description: 'Yunnei generator.' },
    { id: 'yunnei-25kw', name: 'Yunnei 25kW Generator', brand: 'Yunnei', powerKW: 25, type: 'Silent', image: '/images/yunnei-30kw-md40.png', inStock: true, description: 'Yunnei generator.' },
    { id: 'yunnei-23.1kw', name: 'Yunnei 23.1kW Generator', brand: 'Yunnei', powerKW: 23.1, type: 'Silent', image: '/images/yunnei-16kw-md25.png', inStock: true, description: 'Yunnei generator.' },
    { id: 'yunnei-20kw', name: 'Yunnei 20kW Generator', brand: 'Yunnei', powerKW: 20, type: 'Silent', image: '/images/yunnei-16kw-md25.png', inStock: true, description: 'Yunnei generator.' },
    { id: 'weichai-353kw', name: 'Weichai 353kW Generator', brand: 'Weichai', powerKW: 353, type: 'Silent', image: '/images/weichai-500kw.png', inStock: true, description: 'Weichai generator.' },
    { id: 'weichai-330kw', name: 'Weichai 330kW Generator', brand: 'Weichai', powerKW: 330, type: 'Silent', image: '/images/weichai-500kw.png', inStock: true, description: 'Weichai generator.' },
    { id: 'weichai-275kw', name: 'Weichai 275kW Generator', brand: 'Weichai', powerKW: 275, type: 'Silent', image: '/images/weichai-500kw.png', inStock: true, description: 'Weichai generator.' },
    { id: 'last-160kw', name: 'Last 160kW Generator', brand: 'Last', powerKW: 160, type: 'Silent', image: '/images/last-brand-silent.png', inStock: true, description: 'Last brand generator.' },
    { id: 'last-100kw', name: 'Last 100kW Generator', brand: 'Last', powerKW: 100, type: 'Silent', image: '/images/last-brand-silent.png', inStock: true, description: 'Last brand generator.' },
    { id: 'last-75kw', name: 'Last 75kW Generator', brand: 'Last', powerKW: 75, type: 'Silent', image: '/images/last-brand-silent.png', inStock: true, description: 'Last brand generator.' },
    { id: 'last-40kw', name: 'Last 40kW Generator', brand: 'Last', powerKW: 40, type: 'Silent', image: '/images/last-brand-silent.png', inStock: true, description: 'Last brand generator.' },
    { id: 'last-25kw', name: 'Last 25kW Generator', brand: 'Last', powerKW: 25, type: 'Silent', image: '/images/last-brand-silent.png', inStock: true, description: 'Last brand generator.' },
    { id: 'kefo-180kw', name: 'Kefo 180kW Generator', brand: 'Kefo', powerKW: 180, type: 'Silent', image: '/images/kefo-large-silent.png', inStock: true, description: 'Kefo generator.' },
    { id: 'kefo-120kw', name: 'Kefo 120kW Generator', brand: 'Kefo', powerKW: 120, type: 'Silent', image: '/images/kefo-large-silent.png', inStock: true, description: 'Kefo generator.' },
    { id: 'kefo-150kw', name: 'Kefo 150kW Generator', brand: 'Kefo', powerKW: 150, type: 'Silent', image: '/images/kefo-large-silent.png', inStock: true, description: 'Kefo generator.' },
    { id: 'yuchai-120kw-new', name: 'Yuchai 120kW Generator', brand: 'Yuchai', powerKW: 120, type: 'Silent', image: '/images/yuchai-100kw.png', inStock: true, description: 'Yuchai generator.' },
    { id: 'yuchai-92kw', name: 'Yuchai 92kW Generator', brand: 'Yuchai', powerKW: 92, type: 'Silent', image: '/images/yuchai-100kw.png', inStock: true, description: 'Yuchai generator.' },
    { id: 'united-8kw', name: 'United Power 8kW Generator', brand: 'United Power', powerKW: 8, type: 'Silent', image: '/images/united-power-silent.png', inStock: true, description: 'United Power generator.' },
    { id: 'united-7kw', name: 'United Power 7kW Generator', brand: 'United Power', powerKW: 7, type: 'Silent', image: '/images/united-power-silent.png', inStock: true, description: 'United Power generator.' }
];

export const PUMPS: WaterPump[] = [
    {
        id: 'cep-50p',
        name: 'CE Power 50HP Water Pump',
        type: 'Diesel',
        inletSize: '4-Inch',
        maxHead: 60,
        flowRate: 360,
        image: '/images/cep-50p.png',
        inStock: true,
        description: 'High-efficiency CE Power water pump for agricultural and industrial irrigation.',
        specs: { suction: '8m', fuelTank: '15L', engineModel: 'CE-50HP', startSystem: 'Electric' }
    },
    {
        id: 'yc-50p',
        name: 'Yuchai 50HP Diesel Pump',
        type: 'Diesel',
        inletSize: '4-Inch',
        maxHead: 70,
        flowRate: 320,
        image: '/images/yc-50p.png',
        inStock: true,
        description: 'Reliable Yuchai diesel water pump, designed for heavy-duty dewatering and irrigation.',
        specs: { suction: '8m', fuelTank: '12L', engineModel: 'YC-50HP', startSystem: 'Recoil/Electric' }
    },
    {
        id: 'cum-pump-100',
        name: 'Cummins 100HP Fire Pump',
        type: 'High Pressure',
        inletSize: '6-Inch',
        maxHead: 100,
        flowRate: 500,
        image: '/images/cum-pump-100.png',
        inStock: true,
        description: 'High-performance Cummins diesel fire pump system for emergency response.',
        specs: { suction: '9m', fuelTank: '40L', engineModel: 'Cummins 100', startSystem: 'Dual Electric' }
    },
    {
        id: 'perkins-pump-80',
        name: 'Perkins 80HP Irrigation Pump',
        type: 'Diesel',
        inletSize: '4-Inch',
        maxHead: 80,
        flowRate: 400,
        image: '/images/perkins-pump-80.png',
        inStock: true,
        description: 'Efficient Perkins powered water pump for large scale irrigation.',
        specs: { suction: '8m', fuelTank: '25L', engineModel: 'Perkins 80', startSystem: 'Electric' }
    },
    {
        id: 'yunnei-pump-100kw',
        name: 'Yunnei 100kW Industrial Pump',
        type: 'Industrial',
        inletSize: '6-Inch',
        maxHead: 85,
        flowRate: 450,
        image: '/images/yunnei-pump-40.png',
        inStock: true,
        description: 'Large capacity Yunnei industrial pump for mining and flood control.',
        specs: { suction: '8m', fuelTank: '50L', engineModel: 'Yunnei-100kW', startSystem: 'Electric' }
    },
    {
        id: 'gold-slurry-pump-50',
        name: 'Gold Refinement Slurry Pump',
        type: 'Industrial',
        inletSize: '4-Inch',
        maxHead: 90,
        flowRate: 300,
        image: '/images/cep-50p.png',
        inStock: true,
        description: 'High-head water pump designed specifically for gold washing and refinement processes.',
        specs: { suction: '9m', fuelTank: '20L', engineModel: 'Slurry-Pro 50', startSystem: 'Electric' }
    },
    {
        id: 'yunnei-pump-40',
        name: 'Yunnei 40HP Water Pump',
        type: 'Diesel',
        inletSize: '4-Inch',
        maxHead: 50,
        flowRate: 280,
        image: '/images/yunnei-pump-40.png',
        inStock: true,
        description: 'Portable Yunnei diesel water pump for agriculture.',
        specs: { suction: '7m', fuelTank: '10L', engineModel: 'YN-40HP', startSystem: 'Recoil' }
    },
    {
        id: 'kefo-pump-30',
        name: 'Kefo 30HP Water Pump',
        type: 'Diesel',
        inletSize: '3-Inch',
        maxHead: 40,
        flowRate: 180,
        image: '/images/kefo-pump-30.png',
        inStock: true,
        description: 'Small Kefo water pump for domestic and light agricultural use.',
        specs: { suction: '7m', fuelTank: '8L', engineModel: 'KF-30HP', startSystem: 'Recoil' }
    },
    // Adding more pumps from constants.ts
    { id: 'yunnei-600kw-pump', name: 'Yunnei 600kW Pump', brand: 'Yunnei', type: 'Industrial', inletSize: '8-Inch', maxHead: 120, flowRate: 800, image: '/images/pump-120kw-open.png', inStock: true, description: 'High power Yunnei pump engine.', specs: { suction: '9m', fuelTank: '100L', engineModel: 'YN-600', startSystem: 'Electric' } },
    { id: 'yunnei-400kw-pump', name: 'Yunnei 400kW Pump', brand: 'Yunnei', type: 'Industrial', inletSize: '6-Inch', maxHead: 100, flowRate: 530, image: '/images/pump-120kw-open.png', inStock: true, description: 'Reliable Yunnei pump engine.', specs: { suction: '8m', fuelTank: '80L', engineModel: 'YN-400', startSystem: 'Electric' } },
    { id: 'yunnei-334kw-pump', name: 'Yunnei 334kW Pump', brand: 'Yunnei', type: 'Industrial', inletSize: '6-Inch', maxHead: 90, flowRate: 450, image: '/images/pump-120kw-open.png', inStock: true, description: 'Yunnei industrial pump.', specs: { suction: '8m', fuelTank: '60L', engineModel: 'YN-334', startSystem: 'Electric' } },
    { id: 'yunnei-120kw-pump-new', name: 'Yunnei 120kW Pump', brand: 'Yunnei', type: 'Industrial', inletSize: '4-Inch', maxHead: 85, flowRate: 160, image: '/images/pump-120kw-open.png', inStock: true, description: 'Efficient Yunnei pump.', specs: { suction: '8m', fuelTank: '50L', engineModel: 'YN-120', startSystem: 'Electric' } },
    { id: 'weichai-400kw-pump', name: 'Weichai 400kW Pump', brand: 'Weichai', type: 'Industrial', inletSize: '6-Inch', maxHead: 105, flowRate: 530, image: '/images/weichai-pump-300.png', inStock: true, description: 'Weichai pump.', specs: { suction: '9m', fuelTank: '100L', engineModel: 'WC-400', startSystem: 'Electric' } },
    { id: 'last-200kw-pump', name: 'Last 200kW Pump', brand: 'Last', type: 'Industrial', inletSize: '4-Inch', maxHead: 80, flowRate: 260, image: '/images/pump-120kw-open.png', inStock: true, description: 'Last brand pump.', specs: { suction: '8m', fuelTank: '40L', engineModel: 'L-200', startSystem: 'Electric' } },
    { id: 'kefo-180kw-pump', name: 'Kefo 180kW Pump', brand: 'Kefo', type: 'Industrial', inletSize: '4-Inch', maxHead: 75, flowRate: 240, image: '/images/pump-120kw-open.png', inStock: true, description: 'Kefo pump.', specs: { suction: '8m', fuelTank: '40L', engineModel: 'KF-180', startSystem: 'Electric' } },
    { id: 'united-11kw-pump', name: 'United Power 11kW Pump', brand: 'United Power', type: 'Diesel', inletSize: '3-Inch', maxHead: 45, flowRate: 15, image: '/images/cep-50p.png', inStock: true, description: 'United Power pump.', specs: { suction: '7m', fuelTank: '12L', engineModel: 'UP-11', startSystem: 'Electric' } }
];
